name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: cd src ; go get . ; cd .. ; go mod download github.com/ELPanaJose/pairat ; go mod download github.com/manifoldco/promptui ; go get github.com/manifoldco/promptui@v0.9.0

    - name: Test
      run: ./main https://www.youtube.com/watch?v=829pvBHyG6I
